version: '3'

services:
  django:
    build: 
      context: /root/server/django
      dockerfile: Dockerfile
    container_name: django_container
    volumes:
      - /root/server/django:/app
      
      - ./app/static:/static
    command: ["gunicorn", "--bind", "0.0.0.0:8000", "config.wsgi:application"]
    networks:
      - my_network
    
  nginx:
    build: /root/server/nginx
    container_name: nginx_container
    ports:
      - "80:80"
    depends_on:
      - django
    volumes:
      - /root/server/static:/app/static
      - /root/server/nginx:/etc/nginx/conf.d
    networks:
      - my_network

networks:
    my_network:
      driver: bridge